whatsbusy/movies/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

# namespace for users
app_name = "movies"

urlpatterns = [
    # path to function rendering index page
    path('get/<str:movie>', views.get_movie, name="get_movie"),


]

whatsbusy/subscription/urls.py
from django.urls import include, path
from . import views

# namespace for subscriptions
app_name = "subscription"

urlpatterns = [
    # path to function rendering page to get premium subscription
    path('premium/', views.getPremium,
         name="getPremium"),
    # path to function interacting with STRIPE apis for premium subscription
    path('pay/', views.registerPremium,
         name="registerPremium"),
    # path to function to cancel premium subscription
    path('cancel/', views.cancelPremium,
         name="cancelPremium"),

]

whatsbusy/users/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

# namespace for users
app_name = "users"

urlpatterns = [
    # path to function rendering index page
    path('', views.index, name="index"),
    # path to function rendering Registration page
    path('register/', views.register, name="register"),
    # path to function rendering home page
    path('home/', views.home, name="home"),
    # path to function rendering account details page
    path('myaccount/', views.account, name="account")


]

whatsbusy/whatsbusy/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth.urls import views


urlpatterns = [
    # paths for login and authetication
    path('', include('django.contrib.auth.urls')),
    # paths for home, index and registration  pages
    path('', include('users.urls')),
    # paths for subscription handling
    path('subscription/', include('subscription.urls')),
    # paths for Django admin
    path('admin/', admin.site.urls),
    # path for movies
    path('movies/', include('movies.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

whatsbusy/movies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Movie(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    imdb_rating = models.FloatField(max_length=2)

    def __str__(self):
        return self.name

whatsbusy/subscription/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# Subscription model with OnetoOne relationship with the User


class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=False)
    trial = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(max_length=500, default='')
    stripe_token_id = models.CharField(max_length=500, default='')
    stripe_subscription_id = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.stripe_subscription_id

whatsbusy/users/models.py
from django.db import models

# Create your models here.

whatsbusy/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# User registartion form
# Modified and built upon Django default UserCreationForm and User object


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email',
                  'password1', 'password2', )

whatsbusy/movies/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from subscription.models import Subscription
from .models import Movie

# Create your views here.
@login_required
def get_movie(request, movie):
    subscription = Subscription.objects.get(user=request.user)
    movieObj = Movie.objects.get(name=movie)
    context = {"user": request.user,
               "active": subscription.active, "movie": movieObj}
    print(context["active"])
    return render(request, "movie.html", context)

whatsbusy/subscription/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Subscription
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.conf import settings
from .models import Subscription
from users import views
import stripe


# Create your views here.
stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your views here.

# rendering form to get premium
@login_required
def getPremium(request):
    return render(request, 'checkout.html')

# interecting with STRIPE apis to get premium subscription
@login_required
def registerPremium(request):
    subscription_obj = Subscription.objects.get(user=request.user)
    customer_id = subscription_obj.stripe_customer_id
    card_token = request.POST['stripeToken']

    # saving card with the customer
    saveCard(subscription_obj, card_token, customer_id)

    # generating charge
    charge = chargeCustomer(customer_id)

    # Setting up subscription
    subscription_obj = subscribeCustomer(subscription_obj, customer_id)

    subscription_obj.active = True
    trial = subscription_obj.trial
    subscription_obj.save()
    context = {"active": True, "trial": trial}
    return redirect('users:home')


# cancel subscription
@login_required
def cancelPremium(request):
    subscription_obj = Subscription.objects.get(user=request.user)
    subscription_id = subscription_obj.stripe_subscription_id
    stripe_subscription = stripe.Subscription.delete(subscription_id)
    subscription_obj.active = False
    trial = subscription_obj.trial
    subscription_obj.save()
    context = {"active": False, "trial": trial}
    return redirect('users:home')


# link card with customer
def saveCard(subscription, card_token, customer_id):
    if subscription.stripe_token_id == "":
        subscription.stripe_token_id = card_token

        customer = stripe.Customer.modify(
            customer_id,
            source=card_token
        )


# charge customer
def chargeCustomer(customer_id):
    charge = stripe.Charge.create(
        customer=customer_id,
        amount=4999,
        currency='usd'

    )
    return charge


# subscribe a customer
def subscribeCustomer(subscription, customer_id):
    if subscription.active == False and subscription.trial == False:
        stripe_subscription = stripe.Subscription.create(
            customer=customer_id,
            items=[
                {
                    'plan': 'plan_HCy6UA9z08gVnb',
                },
            ],
            trial_period_days=7,
        )
        subscription.stripe_subscription_id = stripe_subscription["id"]
        subscription.trial = True
    else:
        stripe_subscription = stripe.Subscription.create(
            customer=customer_id,
            items=[
                {
                    'plan': 'plan_HCy6UA9z08gVnb',
                },
            ],
        )
        subscription.stripe_subscription_id = stripe_subscription["id"]
    return subscription

whatsbusy/users/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from subscription.models import Subscription
from movies.models import Movie
# Create your views here.


# main/index page
def index(request):
    if request.user.is_authenticated:
        return redirect('users:home')
    else:
        return render(request, 'index.html')


# registeration page
def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login')
        else:
            print("form invalid")
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

# home page
@login_required
def home(request):
    # subscription = Subscription.objects.get(user=request.user)
    movies = Movie.objects.all()
    context = {"movies": movies}
    return render(request, 'home.html', context)


@login_required
def account(request):
    subscription = Subscription.objects.get(user=request.user)
    context = {"user": request.user,
               "active": subscription.active, "trial": subscription.trial}
    return render(request, 'account_home.html', context)

whatsbusy/templates/account_home.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head%}
{% block welcome %}
<li class="nav-item">
    <a class="nav-link">Welcome {{user.username}}</a>
</li>
{% endblock welcome %}
{% block content %}
{% csrf_token %}
<div class="sub-wrapper">
    <div class="sub">

        <p><b>Subscription Status</b></p>
        {% if active%}
        <h3>You have Premium subscription</h3>
        <button type="submit" class="btn btn-success" onclick="cancel()">CANCEL</button>

        {%else%}
        {% if trial%}
        <h3>You do not have Premium Subscription You do not have trial left!</h3>
        <button type="submit" class="btn btn-success" onclick="premium()">GET PREMIUM</button>
        {%else%}
        <h3>You do not have Premium Subscription You have 7 day trial left!</h3>
        <button type="submit" class="btn btn-success" onclick="premium()">GET PREMIUM</button>

        {% endif %}
        {% endif %}
    </div>
</div>

<script>
    function cancel() {
        location.href = "{% url 'subscription:cancelPremium'%}"
    }

    function premium() {
        location.href = "{% url 'subscription:getPremium'%}"
    }
</script>

{% endblock %}

whatsbusy/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock title%}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- <script src="https://js.stripe.com/v3/"></script> -->
    {% block head %} {% endblock head%}
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">



        <!-- Links -->
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'users:home' %}">Home</a>
        <ul class="navbar-nav ml-auto">
            {% block welcome %} {% endblock welcome %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:account' %}">My Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>


        {% else %}
        <a class="navbar-brand" href="{% url 'users:index' %}">Home</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
        </ul>

        {% endif %}

        </ul>
    </nav>
    <div class="content" style="width: 100%; height: 100%;">
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

whatsbusy/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head%}
{% block welcome %}
<li class="nav-item">
    <a class="nav-link">Welcome {{user.username}}</a>
</li>
{% endblock welcome %}
{% block content %}
{% csrf_token %}
<div class="sub-wrapper">
    <div class="sub">
        <h3>Movies</h3>
        {% for movie in movies %}
        <h5><a href="{% url 'movies:get_movie' movie %}"> {{movie}}</a></h5>
        {% endfor %}
    </div>
</div>

<!-- <script>
    function cancel() {
        location.href = "{% url 'subscription:cancelPremium'%}"
    }

    function premium() {
        location.href = "{% url 'subscription:getPremium'%}"
    }
</script> -->

{% endblock content %}

whatsbusy/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Main {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock head%}
{% block content %}
{% csrf_token %}
<div class="welcome-wrapper">
    <div class="welcome">
        <h1>Welcome To WhatsBusy</h1>
    </div>
</div>

{% endblock %}

whatsbusy/templates/movies/movie.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head%}
{% block welcome %}
<li class="nav-item">
    <a class="nav-link">Welcome {{user.username}}</a>
</li>
{% endblock welcome %}
{% block content %}
{% csrf_token %}
<div class="sub-wrapper">
    <div class="sub">
        <h5> {{movie}}</h5>
        <p>IMDB: {{movie.imdb_rating}}</p>
        <p>Description: {{movie.description}}</p>

        <button id='javascript:' onclick='startmovie("{{active}}")'>Watch Now</button>
        <div id="playmovie"></div>
        <br>

    </div>
</div>

<script>

    function startmovie( active ) {
        console.log( active )
        if ( active == "True" ) {

            document.getElementById( "playmovie" ).innerHTML = "<video width='530' height='330' controls><source src='{% static 'Were.the.Millers.2013.mp4'%}' type='video/mp4'>Not Supported </source> </video>"
        } else {
            if ( confirm( "You Do not have premium, Click Ok to get Premium" ) ) {
                location.href = "{% url 'subscription:getPremium'%}"
            }
        }
    }
</script>

{% endblock content %}

whatsbusy/templates/subscription/checkout.html
{% extends "base.html" %}
{% block title %} Premium {%endblock title%}
{% block head %}

{% load static %}


<!-- <link rel="stylesheet" href="{% static 'css/checkout.css' %}"> -->
<!-- <script src="{% static 'js/checkout.js' %}"></script> -->

{% endblock head%}
{% block content %}
<!-- <style type="text/css">
        .StripeElement {
                box-sizing: border-box;

                height: 40px;

                padding: 10px 12px;

                border: 1px solid transparent;
                border-radius: 4px;
                background-color: white;

                box-shadow: 0 1px 3px 0 #e6ebf1;
                -webkit-transition: box-shadow 150ms ease;
                transition: box-shadow 150ms ease;
        }

        .StripeElement--focus {
                box-shadow: 0 1px 3px 0 #cfd7df;
        }

        .StripeElement--invalid {
                border-color: #fa755a;
        }

        .StripeElement--webkit-autofill {
                background-color: #fefde5 !important;
        }
</style> -->

<div class="form row">
        <div class="col">
                <div class="row heading-wrapper">
                        <div class="heading">
                                <h3>Premium Subscription is $49.99</h3>
                        </div>
                </div>
                <script src="https://js.stripe.com/v3/"></script>
                <div class="row">
                        <div class="col">
                                <form action="{% url 'subscription:registerPremium' %}" method="post" id="payment-form">
                                        {% csrf_token %}
                                        <div class="form-row row label-heading">
                                                <label for="card-element">
                                                        Enter Credit or debit card
                                                </label>
                                        </div>
                                        <div class="row card-details">
                                                <div id="card-element">
                                                        <!-- A Stripe Element will be inserted here. -->
                                                </div>

                                                <!-- Used to display form errors. -->
                                                <div id="card-errors" role="alert"></div>
                                        </div>
                                        <div class="row button-submit">
                                                <button type="submit" class="btn btn-primary">Submit Payment</button>
                                        </div>
                                </form>
                        </div>
                </div>
        </div>
</div>

<!-- <script src="{% static "js/checkout.js" %}"></script> -->
<!-- <script>

        // Create a Stripe client.
        var stripe = Stripe('pk_test_dAo4ju8bOSf3zlqur5QQpuE200ho5AR9vZ');

        // Create an instance of Elements.
        var elements = stripe.elements();

        // Custom styling can be passed to options when creating an Element.
        // (Note that this demo uses a wider set of styles than the guide below.)
        var style = {
                base: {
                        color: '#32325d',
                        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                        fontSmoothing: 'antialiased',
                        fontSize: '16px',
                        '::placeholder': {
                                color: '#aab7c4'
                        }
                },
                invalid: {
                        color: '#fa755a',
                        iconColor: '#fa755a'
                }
        };

        // Create an instance of the card Element.
        var card = elements.create('card', { style: style });

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function (event) {
                var displayError = document.getElementById('card-errors');
                if (event.error) {
                        displayError.textContent = event.error.message;
                } else {
                        displayError.textContent = '';
                }
        });

        // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function (event) {
                event.preventDefault();

                stripe.createToken(card).then(function (result) {
                        if (result.error) {
                                // Inform the user if there was an error.
                                var errorElement = document.getElementById('card-errors');
                                errorElement.textContent = result.error.message;
                        } else {
                                // Send the token to your server.
                                stripeTokenHandler(result.token);
                        }
                });
        });

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
                // Insert the token ID into the form so it gets submitted to the server
                var form = document.getElementById('payment-form');
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'stripeToken');
                hiddenInput.setAttribute('value', token.id);
                form.appendChild(hiddenInput);

                // Submit the form
                form.submit();
        }

</script> -->
<link rel="stylesheet" href="{% static 'css/checkout1.css' %}">
<script src="{% static 'js/checkout.js' %}"></script>
{% endblock %}